on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        # 这里使用java11的环境, 其他项目在github action中找到对应的语言环境就行
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        # 这里maven的打包命令, 其他项目修改为对应的打包命令
        run: |
          mvn package
      - name: scp jar upload cloud server
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          scp_source: target/jiajiawork3-0.0.1-SNAPSHOT.jar
          scp_target: /home/zntzhang
          host: ${{secrets.SERVER_IP}}
          username: root
          password: ${{secrets.SERVER_PWD}}
      - name: Deploy to cloud server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: root
          password: ${{secrets.SERVER_PWD}}
          port: 22
          script: cd /home/zntzhang;
                  ps -ef | grep jiajiawork3-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}' | xargs kill -9;
                  source /etc/profile;
                  nohup java -jar jiajiawork3-0.0.1-SNAPSHOT.jar > jiajiawork3.log 2>&1 &
