on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        # 这里使用java11的环境, 其他项目在github action中找到对应的语言环境就行
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        # 这里maven的打包命令, 其他项目修改为对应的打包命令
        run: |
          mvn package
      - name: scp jar upload cloud server
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          scp_source: target/jiajiawork-0.0.3-SNAPSHOT.jar.jar
          scp_target: /home/zntzhang
          host: ${{secrets.SERVER_IP}}
          username: zntzhang
          password: ${{secrets.SERVER_PWD}}
      - name: Deploy to cloud server
        uses: fifsky/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          user: zntzhang
          pass: ${{secrets.SERVER_PWD}}
          command: ps -ef |grep java |awk '{print $2}'|xargs kill -9 && cd /home/zntzhang && nohup java -jar jiajiawork3-0.0.1-SNAPSHOT.jar > jiajiawork3.log 2>&1 &
